name: Automatic Issue Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read Labels JSON
        id: labels
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = './.github/labels.json';
            try {
              const content = fs.readFileSync(path);
              const labels = JSON.parse(content);
              return labels;
            } catch (error) {
              core.setFailed(`Error reading labels: ${error.message}`);
              return null;
            }

      - name: Check issue title format
        id: check_format
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = context.payload.issue.title;
            const labels = ${{ steps.labels.outputs.result }}
            
            if (!labels) {
              core.setFailed('Labels configuration not found');
              return false;
            }

            const labelGroups = issueTitle.match(/\[([^\]]+)\]/g);
            
            if (!labelGroups) {
              return false;
            }

            if (labelGroups.length !== Object.keys(labels).length) {
              return false;
            }

            const isValid = labelGroups.every((group, index) => {
              const tags = group.match(/[^,\[\]]+/g).map(tag => tag.trim());
              const field = Object.keys(labels)[index];
              const validLabels = labels[field];
              return tags.every(tag => validLabels.includes(tag));
            });

            return isValid;

      - name: Add comment and close issue if format is invalid
        if: ${{ steps.check_format.outputs.result == 'false' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const comment = `
              Merhaba @${context.actor}, bu issue'nun başlığı belirlenen formata uymuyor.
              Lütfen başlığı "AD-SOYAD [ALAN][STAJ YERİ][STAJ TİPİ][STAJ SÜRESİ]" formatına uygun hale getirin.
              Örnekler için:
              https://github.com/VB10/staj_2024/issues/1
              Bu işlemi tamamladıktan sonra issue'yu başlığını güncellemen yeterli olacak.
            `;
            // Issue'ya yorum ekle
            await octokit.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: comment
            });
            // Issue'yu kapat
            await octokit.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: 'closed'
            });

      - name: Label the issue
        uses: actions/github-script@v7
        if: ${{ steps.check_format.outputs.result == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.issue.title;
            const issue_number = context.issue.number;
            const issue_author = context.payload.issue.user.login;
            const issueUrl = context.payload.issue.html_url;
            const issueState = context.payload.issue.state;
            const labelsToAdd = new Set(); // Use Set to avoid duplicates
            const fields = ${{ steps.labels.outputs.result }}

            const labelGroups = title.match(/\[([^\]]+)\]/g);
            
            if (!labelGroups) {
              return;
            }

            labelGroups.forEach(group => {
              const tags = group.match(/[^,\[\]]+/g).map(tag => tag.trim());
              tags.forEach(tag => {
                for (const [field, validLabels] of Object.entries(fields)) {
                  if (validLabels.includes(tag)) {
                    labelsToAdd.add(tag);
                    break; // Exit loop once we find a match
                  }
                }
              });
            });

            const wasClosed = issueState === 'closed';

            if (wasClosed) {
              await octokit.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                state: 'open'
              });
            }

            if (labelsToAdd.size > 0) {
              await octokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                labels: Array.from(labelsToAdd)
              });
            }

            await octokit.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                assignees: [issue_author]
              });

            const comment = `
              Merhaba @${context.actor}, staj başvurun başarı ile taglendi..
              Lütfen staj bulduktan sonra buraya gelip kapatmayı unutma.
              Şimdiden bol şans ve sakın unutma staj ne başlangıç ne son çok çalışmak lazım.
            `;
            await octokit.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: comment
              });
