name: Sync Labels

on:
  push:
    paths:
      - '.github/labels.json'
    branches:
      - main

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Create/Sync Labels
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const labelsData = JSON.parse(fs.readFileSync('.github/labels.json', 'utf8'));
            
            // Get existing labels
            const existingLabels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.name,
            });
            
            const existingLabelNames = existingLabels.data.map(label => label.name);
            
            // Create context labels
            for (const contextLabel of labelsData.context) {
              if (!existingLabelNames.includes(contextLabel)) {
                try {
                  // Generate random hex color without '#'
                  const randomColor = Math.floor(Math.random()*16777215).toString(16).padStart(6, '0');
                  
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.name,
                    name: contextLabel,
                    color: randomColor,
                    description: `Context: ${contextLabel}`
                  });
                  console.log(`Created label: ${contextLabel} with color: #${randomColor}`);
                } catch (error) {
                  console.error(`Error creating label ${contextLabel}:`, error);
                }
              }
            } 